version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://grocery_user:grocery_password@db:5432/grocery_db
    depends_on:
      - db
    command: ["flask", "db", "upgrade", "&&", "flask", "run", "--host", "0.0.0.0"]
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: grocery_user
      POSTGRES_PASSWORD: grocery_password
      POSTGRES_DB: grocery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: