"""Add category_imageurl to categories table

Revision ID: 357827e5cea8
Revises: 
Create Date: 2025-04-20 18:06:20.223081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357827e5cea8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_imageurl', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('category_imageurl')

    # ### end Alembic commands ###
